---
- name: Deploy application using Docker Compose
  hosts: all
  become: true
  tasks:
    - name: Ensure /app directory exists
      file:
        path: /app
        state: directory

    - name: Pull latest docker images
      become: false
      shell: docker-compose pull
      args:
        chdir: /app

    - name: Restart containers
      become: false
      shell: docker-compose up -d
      args:
        chdir: /app
