- name: Deploy Nexus
  hosts: nexus
  tasks:
    - name: Pull and run docker-compose
      ansible.builtin.shell: |
        mkdir -p /app
        cd /app
        docker-compose pull
        docker-compose up -d
- name: Deploy Nexus
  hosts: nexus
  tasks:
    - name: Pull and run docker-compose
      ansible.builtin.shell: |
        mkdir -p /app
        cd /app
        docker-compose pull
        docker-compose up -d
