---
- name: Deploy Nexus Repository Manager
  hosts: all
  become: yes
  vars:
    nexus_version: "3.49.1"  # You can adjust the version here
    nexus_data_dir: /opt/nexus-data
  tasks:
    - name: Ensure docker is installed
      ansible.builtin.package:
        name: docker
        state: present

    - name: Ensure docker-py python module is installed (required for Docker module)
      ansible.builtin.pip:
        name: docker
        state: present

    - name: Create Nexus data directory
      ansible.builtin.file:
        path: "{{ nexus_data_dir }}"
        state: directory
        owner: 200
        group: 200
        mode: '0755'

    - name: Pull Nexus Docker image
      community.docker.docker_image:
        name: sonatype/nexus3
        tag: "{{ nexus_version }}"
        source: pull

    - name: Run Nexus container
      community.docker.docker_container:
        name: nexus
        image: sonatype/nexus3:{{ nexus_version }}
        state: started
        restart_policy: always
        ports:
          - "8081:8081"
        volumes:
          - "{{ nexus_data_dir }}:/nexus-data"
