---
- name: Deploy Nexus Repository Manager
  hosts: all
  become: true
  vars:
    nexus_version: "3.49.1"
    nexus_data_dir: /opt/nexus-data

  tasks:
    - name: Ensure Docker is installed (Debian/Ubuntu)
      ansible.builtin.apt:
        name: docker.io
        state: present
        update_cache: yes
      when: ansible_facts['os_family'] == "Ubuntu"

    - name: Ensure pip is installed
      ansible.builtin.package:
        name: python3-pip
        state: present

    - name: Install docker Python module
      ansible.builtin.pip:
        name: docker
        executable: pip3

    - name: Create Nexus data directory
      ansible.builtin.file:
        path: "{{ nexus_data_dir }}"
        state: directory
        owner: 200
        group: 200
        mode: '0755'

    - name: Pull Nexus Docker image
      community.docker.docker_image:
        name: sonatype/nexus3
        tag: "{{ nexus_version }}"
        source: pull

    - name: Run Nexus container
      community.docker.docker_container:
        name: nexus
        image: sonatype/nexus3:{{ nexus_version }}
        state: started
        restart_policy: always
        published_ports:
          - "8081:8081"
        volumes:
          - "{{ nexus_data_dir }}:/nexus-data"
